; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://platformio.org

[platformio]
src_dir = firmware/src
include_dir = firmware/include
lib_dir = firmware/lib
data_dir = firmware/data
test_dir = firmware/test

[env:xiaoble]
platform = https://github.com/Seeed-Studio/platform-seeedboards.git
board = seeed-xiao-afruitnrf52-nrf52840
framework = arduino

; --- ERZWEINGE 3DX MOUSE EMULATION FÜR NRF52 (OFFIZIELLE SPEZIFIKATIONEN) ---
; Im nRF52-Framework von Adafruit/Seeed werden VID/PID über build_flags übergeben:
build_flags = 
	-DUSE_TINYUSB
	-DUSB_VID=0x046D
	-DUSB_PID=0xC626
	-DUSB_MANUFACTURER='"3Dconnexion"'
	-DUSB_PRODUCT='"SpaceMouse Wireless"'

lib_deps = 
	infineon/XENSIV 3D Magnetic Sensor TLx493D@^1.1.0
	bxparks/AceButton@^1.10.1
	adafruit/Adafruit NeoPixel@^1.12.3
